osism/ansible-collection-commons

.github/workflows/test-sysdig.yml
README.md
molecule/requirements.txt
molecule/sysdig/ansible.cfg
molecule/sysdig/converge.yml
molecule/sysdig/create.yml
molecule/sysdig/destroy.yml
molecule/sysdig/group_vars/all.yml
molecule/sysdig/molecule.yml
molecule/sysdig/prepare.yml
molecule/sysdig/tests/test_default.py
roles/sysdig/.information.yml
roles/sysdig/README.md
roles/sysdig/defaults/main.yml
roles/sysdig/gilt.yml
roles/sysdig/meta/main.yml
roles/sysdig/tasks/install-Debian.yml
roles/sysdig/tasks/main.yml

Add sysdig role

---

README.md

README: fix sysdig test badge

---

.github/workflows/test-lynis.yml
README.md
molecule/lynis/ansible.cfg
molecule/lynis/converge.yml
molecule/lynis/create.yml
molecule/lynis/destroy.yml
molecule/lynis/group_vars/all.yml
molecule/lynis/molecule.yml
molecule/lynis/prepare.yml
molecule/lynis/tests/test_default.py
roles/lynis/.information.yml
roles/lynis/README.md
roles/lynis/defaults/main.yml
roles/lynis/gilt.yml
roles/lynis/meta/main.yml
roles/lynis/tasks/install-Debian.yml
roles/lynis/tasks/main.yml

Add lynis role

---

roles/lynis/tasks/install-Debian.yml
roles/sysdig/tasks/install-Debian.yml

Set apt_repository mode = 0600

---

.github/workflows/test-trivy.yml
README.md
molecule/trivy/ansible.cfg
molecule/trivy/converge.yml
molecule/trivy/create.yml
molecule/trivy/destroy.yml
molecule/trivy/group_vars/all.yml
molecule/trivy/molecule.yml
molecule/trivy/prepare.yml
molecule/trivy/tests/test_default.py
roles/trivy/.information.yml
roles/trivy/README.md
roles/trivy/defaults/main.yml
roles/trivy/gilt.yml
roles/trivy/meta/main.yml
roles/trivy/tasks/install-Debian.yml
roles/trivy/tasks/main.yml

Add trivy role

---

.github/workflows/test-sshconfig.yml
README.md
molecule/sshconfig/ansible.cfg
molecule/sshconfig/converge.yml
molecule/sshconfig/create.yml
molecule/sshconfig/destroy.yml
molecule/sshconfig/group_vars/all.yml
molecule/sshconfig/molecule.yml
molecule/sshconfig/prepare.yml
roles/sshconfig/.information.yml
roles/sshconfig/README.md
roles/sshconfig/defaults/main.yml
roles/sshconfig/gilt.yml
roles/sshconfig/meta/main.yml
roles/sshconfig/tasks/main.yml
roles/sshconfig/templates/config.j2

Add sshconfig role

---

roles/hddtemp/.information.yml
roles/hddtemp/README.md
roles/hddtemp/defaults/main.yml
roles/hddtemp/files/hddtemp
roles/hddtemp/gilt.yml
roles/hddtemp/handlers/main.yml
roles/hddtemp/meta/main.yml
roles/hddtemp/tasks/main.yml
roles/motd/.information.yml
roles/motd/README.md
roles/motd/gilt.yml
roles/motd/meta/main.yml
roles/motd/tasks/main.yml
roles/rng/.information.yml
roles/rng/README.md
roles/rng/defaults/main.yml
roles/rng/gilt.yml
roles/rng/meta/main.yml
roles/rng/tasks/main.yml
roles/smartd/.information.yml
roles/smartd/README.md
roles/smartd/defaults/main.yml
roles/smartd/files/smartmontools
roles/smartd/gilt.yml
roles/smartd/handlers/main.yml
roles/smartd/meta/main.yml
roles/smartd/tasks/main.yml

Import some osism.common roles

---

roles/cleanup/.information.yml
roles/cleanup/README.md
roles/cleanup/gilt.yml
roles/cleanup/library/scan_services.py
roles/cleanup/meta/main.yml
roles/cleanup/tasks/main.yml
roles/cleanup/tasks/services.yml
roles/cleanup/tasks/timers.yml

Add cleanup role

---

.ansible-lint
.github/workflows/syntax-ansible.yml

https://github.com/ansible/ansible-lint/issues/644

cleanup: skip ansible-lint for services.yml file

---

molecule/lynis/create.yml
molecule/lynis/destroy.yml
molecule/sshconfig/create.yml
molecule/sshconfig/destroy.yml
molecule/sysdig/create.yml
molecule/sysdig/destroy.yml
molecule/trivy/create.yml
molecule/trivy/destroy.yml
roles/motd/tasks/main.yml

ansible-lint: fix E208

---

roles/motd/defaults/main.yml
roles/motd/tasks/main.yml

motd: overall improvements

---

gilt.yml

Add gilt.yml file

---

roles/hddtemp/handlers/main.yml
roles/hddtemp/tasks/main.yml
roles/lynis/tasks/install-Debian.yml
roles/rng/tasks/main.yml
roles/smartd/handlers/main.yml
roles/smartd/tasks/main.yml
roles/sysdig/tasks/install-Debian.yml
roles/trivy/tasks/install-Debian.yml

Move "become" to the top of the tasks

---

.ansible-lint
roles/motd/tasks/main.yml

motd: stop the motd-news service only if it exists

---

molecule/requirements.txt

Test was moved to Github workflows.

molecule: remove ansible-lint requirement

---

roles/firewall/.information.yml
roles/firewall/README.md
roles/firewall/defaults/main.yml
roles/firewall/gilt.yml
roles/firewall/meta/main.yml
roles/firewall/tasks/main.yml

Add initial firewall role

---

roles/firewall/handlers/main.yml
roles/firewall/tasks/main.yml
roles/firewall/templates/ufw.conf.j2

ufw: add ufw.conf configuration file

---

roles/firewall/handlers/main.yml

ufw: fix handler name

---

roles/facts/tasks/main.yml

facts: fix path to fact files

---

roles/docker_compose/.information.yml
roles/docker_compose/README.md
roles/docker_compose/defaults/main.yml
roles/docker_compose/gilt.yml
roles/docker_compose/meta/main.yml
roles/docker_compose/tasks/install-file.yml
roles/docker_compose/tasks/install-package.yml
roles/docker_compose/tasks/install-url.yml
roles/docker_compose/tasks/main.yml

Add docker_compose role

---

roles/configuration/.information.yml
roles/configuration/README.md
roles/configuration/defaults/main.yml
roles/configuration/gilt.yml
roles/configuration/meta/main.yml
roles/configuration/tasks/git.yml
roles/configuration/tasks/main.yml
roles/configuration/templates/config.j2

Add configuration role

---

README.md

README: add missing roles

---

roles/packages/defaults/main.yml

packages: install jq

---

README.md
roles/network/README.md
roles/network/defaults/main.yml
roles/network/files/interfaces/01-netcfg.yaml
roles/network/gilt.yml
roles/network/handlers/main.yml
roles/network/meta/main.yml
roles/network/tasks/cleanup-interfaces.yml
roles/network/tasks/lldpd.yml
roles/network/tasks/main.yml
roles/network/tasks/type-interfaces.yml
roles/network/templates/interfaces/all_interfaces.j2
roles/network/templates/interfaces/device.j2
roles/network/vars/interfaces/ubuntu-16.04.yml
roles/network/vars/interfaces/ubuntu-18.04.yml
roles/network/vars/interfaces/ubuntu-20.04.yml

Imported from https://github.com/osism/ansible-network

Add osism.network ansible role

---

roles/proxy/defaults/main.yml

proxy: yes -> true

---

roles/packages/defaults/main.yml
roles/packages/tasks/main.yml

packages: yes -> true

---

roles/cleanup/tasks/packages.yml

cleanup: yes -> true

---

roles/configuration/tasks/git.yml

configuration: yes -> true

---

roles/repository/defaults/main.yml

repositories: cleanup repositories

---

roles/cleanup/defaults/main.yml
roles/kernel_modules/defaults/main.yml
roles/microcode/defaults/main.yml
roles/packages/defaults/main.yml
roles/proxy/defaults/main.yml
roles/resolvconf/defaults/main.yml
roles/services/defaults/main.yml

Add extra/default variables

---

.github/workflows/publish-collection.yml

github: add get_version job to the publish collection workflow

---

.information.yml
gilt.yml

Remove gilt configuration

---

roles/proxy/defaults/main.yml
roles/proxy/tasks/Debian.yml
roles/proxy/tasks/RedHat.yml
roles/proxy/tasks/main.yml

proxy: improve proxy_proxies != {} handling

---

roles/timezone/tasks/main.yml

timezone: add missing become

---

.github/workflows/check-yaml-syntax.yml
.yamllint.yml
molecule/default/prepare/configuration.yml
molecule/default/prepare/docker_compose.yml
molecule/default/prepare/microcode.yml
molecule/default/prepare/motd.yml
molecule/default/prepare/podman.yml
molecule/default/prepare/repository.yml
molecule/default/prepare/trivy.yml
roles/hosts/defaults/main.yml
roles/lynis/defaults/main.yml
roles/lynis/tasks/install-Debian.yml
roles/network/defaults/main.yml
roles/network/tasks/cleanup-interfaces.yml
roles/network/tasks/type-interfaces.yml
roles/operator/tasks/main.yml
roles/podman/tasks/install-Debian.yml
roles/repository/handlers/main.yml
roles/repository/tasks/main.yml
roles/sysctl/tasks/sysctl.yml
roles/sysdig/tasks/install-Debian.yml
roles/trivy/defaults/main.yml
roles/trivy/tasks/install-Debian.yml

Fix yamllint issues

---

roles/network/defaults/main.yml

network_allow_service_restart = false
network_restart_method = nothing

network: change defaults

---

roles/facts/files/docker_containers.fact

facts: fix docker_containers fact

---

roles/state/tasks/main.yml

state: use 0644

---

roles/facts/defaults/main.yml
roles/facts/files/docker_containers.fact
roles/facts/files/docker_images.fact

facts: add docker_images fact

---

roles/cleanup/tasks/packages.yml
roles/configuration/tasks/git.yml
roles/docker_compose/tasks/install-file.yml
roles/docker_compose/tasks/install-package.yml
roles/docker_compose/tasks/install-url.yml
roles/lynis/tasks/install-Debian.yml
roles/microcode/tasks/main.yml
roles/motd/tasks/main.yml
roles/network/tasks/lldpd.yml
roles/network/tasks/type-interfaces.yml
roles/packages/tasks/main.yml
roles/podman/tasks/install-Debian.yml
roles/repository/tasks/main.yml
roles/sysdig/tasks/install-Debian.yml
roles/trivy/tasks/install-Debian.yml

Wait for /var/lib/dpkg/lock

---

roles/cleanup/tasks/packages.yml
roles/configuration/tasks/git.yml
roles/docker_compose/tasks/install-file.yml
roles/docker_compose/tasks/install-package.yml
roles/docker_compose/tasks/install-url.yml
roles/lynis/tasks/install-Debian.yml
roles/microcode/tasks/main.yml
roles/motd/tasks/main.yml
roles/network/tasks/lldpd.yml
roles/network/tasks/type-interfaces.yml
roles/packages/tasks/main.yml
roles/podman/tasks/install-Debian.yml
roles/repository/tasks/main.yml
roles/sysdig/tasks/install-Debian.yml
roles/trivy/tasks/install-Debian.yml

Improve "Wait for /var/lib/dpkg/lock"

---

roles/docker_compose/tasks/main.yml
roles/docker_compose/templates/docker-compose.service.j2

docker_compose: add systemd unit file

---

roles/docker_compose/templates/docker-compose.service.j2

docker_compose: remove /

---

roles/hosts/defaults/main.yml
roles/hosts/tasks/type-block.yml
roles/hosts/templates/hosts-template.j2

hosts: add hosts_ignore parameter

---

README.md
roles/ipmitool/defaults/main.yml
roles/ipmitool/meta/main.yml
roles/ipmitool/tasks/install-Debian.yml
roles/ipmitool/tasks/main.yml
roles/ipmitool/templates/module-load.conf.j2

Add ipmitool role

---

README.md
roles/zabbix_configuration/defaults/main.yml
roles/zabbix_configuration/meta/main.yml
roles/zabbix_configuration/tasks/main.yml

Add initial zabbix_configuration role

---

roles/zabbix_configuration/defaults/main.yml
roles/zabbix_configuration/files/template-glance.yaml
roles/zabbix_configuration/tasks/main.yml

zabbix_configuration: improvements & glance template

---

roles/zabbix_configuration/defaults/main.yml
roles/zabbix_configuration/files/template-glance.yaml
roles/zabbix_configuration/files/template-horizon.yaml
roles/zabbix_configuration/files/template-keystone.yaml

zabbix_configuration: add further templates

---

README.md
roles/ipmitool/tasks/install-Debian.yml
roles/zabbix_host/defaults/main.yml
roles/zabbix_host/meta/main.yml
roles/zabbix_host/tasks/main.yml

Add initial zabbix_host role

---

roles/zabbix_host/defaults/main.yml
roles/zabbix_host/tasks/main.yml

zabbix_host: create host

---

roles/zabbix_host/defaults/main.yml
roles/zabbix_host/tasks/main.yml

zabbix_host: add zabbix_host_inventory

---

roles/zabbix_host/defaults/main.yml
roles/zabbix_host/tasks/main.yml

zabbix_host: assign templates

---

roles/zabbix_configuration/files/template-glance.yaml
roles/zabbix_configuration/files/template-horizon.yaml
roles/zabbix_configuration/files/template-keystone.yaml

zabbix_configuration: fix exsiting templates

---

roles/zabbix_configuration/defaults/main.yml
roles/zabbix_configuration/files/template-glance.yaml
roles/zabbix_configuration/files/template-horizon.yaml
roles/zabbix_configuration/files/template-keystone.yaml
roles/zabbix_configuration/files/template-mariadb.yaml
roles/zabbix_host/defaults/main.yml
roles/zabbix_host/tasks/main.yml

zabbix_configuration: add rabbitmq & mariadb templates

---

roles/zabbix_host/tasks/main.yml

zabbix_host: fix wrong template name

---

roles/zabbix_configuration/defaults/main.yml
roles/zabbix_configuration/files/template-rabbitmq.yaml
roles/zabbix_configuration/tasks/main.yml
roles/zabbix_host/tasks/main.yml

zabbix_configuration: use custom rabbitmq template

---

roles/zabbix_host/tasks/main.yml

zabbix_host: fix zabbix server port

---

roles/zabbix_host/defaults/main.yml
roles/zabbix_host/tasks/main.yml

zabbix_host: add memcached

---

README.md
roles/zabbix_cluster/defaults/main.yml
roles/zabbix_cluster/meta/main.yml
roles/zabbix_cluster/tasks/main.yml

Add zabbix_cluster role

---

roles/zabbix_cluster/defaults/main.yml
roles/zabbix_configuration/defaults/main.yml

zabbix_configuration: add host groups

---

galaxy.yml

galaxy: v0.3.0

---

roles/docker_compose/templates/docker-compose.service.j2

docker-compose: use default target

---

galaxy.yml

galaxy: 0.4.0

---

roles/configuration/tasks/git.yml

typo repositroy -> repository

---

roles/network/defaults/main.yml
roles/network/tasks/type-netplan.yml

network: add netplan support (pt. 3)

---

roles/network/handlers/main.yml
roles/network/tasks/cleanup-interfaces.yml
roles/network/tasks/lldpd.yml
roles/network/tasks/type-interfaces.yml
roles/network/tasks/type-netplan.yml

network: add missing becomes

---

roles/network/tasks/type-netplan.yml

network: allow use of variables as dictionary keys

---

roles/configuration/defaults/main.yml
roles/configuration/tasks/git.yml

git: set package name

---

roles/docker_compose/defaults/main.yml
roles/docker_compose/tasks/install-container.yml
roles/docker_compose/templates/docker-compose.j2

docker-compose: add install type container

---

molecule/default/prepare/kubectl.yml
molecule/default/prepare/motd.yml
molecule/default/prepare/podman.yml
molecule/default/prepare/repository.yml
molecule/default/prepare/trivy.yml

molecule: use apt task

---

meta/runtime.yml

meta: fix required ansible version

---

roles/network/defaults/main.yml
roles/network/tasks/type-netplan.yml

netplan: add network_netplan_file argument

---

molecule/default/vars/hosts.yml
roles/hosts/defaults/main.yml
roles/hosts/tasks/type-block.yml
roles/hosts/templates/hosts-template.j2

hosts: add hosts_interface argument

---

roles/docker_compose/tasks/main.yml

feature redhat for role docker_compose, fail if not Debian

---

roles/hosts/templates/hosts-template.j2

hosts: set default if hosts_interface is not set

---

roles/network/defaults/main.yml
roles/network/tasks/type-netplan.yml

network: start/enable networkd-dispatcher service

---

roles/network/defaults/main.yml
roles/network/tasks/type-netplan.yml

network: ensure that the networkd-dispatcher package is installed

---

.github/scripts/generate-role-workflows.sh
.github/templates/test-role.yml.j2
.github/workflows/test-role-cleanup.yml
.github/workflows/test-role-docker_compose.yml
.github/workflows/test-role-facts.yml
.github/workflows/test-role-hostname.yml
.github/workflows/test-role-hosts.yml
.github/workflows/test-role-kompose.yml
.github/workflows/test-role-kubectl.yml
.github/workflows/test-role-microcode.yml
.github/workflows/test-role-motd.yml
.github/workflows/test-role-operator.yml
.github/workflows/test-role-packages.yml
.github/workflows/test-role-podman.yml
.github/workflows/test-role-proxy.yml
.github/workflows/test-role-repository.yml
.github/workflows/test-role-resolvconf.yml
.github/workflows/test-role-services.yml
.github/workflows/test-role-sshconfig.yml
.github/workflows/test-role-state.yml
.github/workflows/test-role-sysctl.yml
.github/workflows/test-role-systohc.yml
.github/workflows/test-role-trivy.yml
.gitignore
molecule/default/molecule.yml

github: fix molecule jobs

---

.github/scripts/generate-role-workflows.sh
.github/workflows/test-role-timezone.yml

github: add timezone workflow

---

galaxy.yml

galaxy: 0.5.0

---

galaxy.yml

galaxy: fix "authors list must not be greater than 64 characters"

---

galaxy.yml

galaxy: 0.6.0

---

meta/runtime.yml

meta: allow use of ansible 2.11

---

roles/hosts/defaults/main.yml
roles/hosts/tasks/type-block.yml
roles/hosts/templates/hosts-template.j2

hosts: add hosts_enable parameter

---

roles/hosts/tasks/type-block.yml
roles/hosts/templates/hosts-template.j2

hosts: sort the list of hosts

---

roles/cleanup/tasks/packages-Debian.yml
roles/configuration/tasks/git.yml
roles/docker_compose/tasks/install-container.yml
roles/docker_compose/tasks/install-package.yml
roles/docker_compose/tasks/install-url.yml
roles/ipmitool/tasks/install-Debian.yml
roles/kompose/tasks/install-url.yml
roles/kubectl/tasks/install-Debian.yml
roles/lynis/tasks/install-Debian.yml
roles/microcode/tasks/main.yml
roles/motd/tasks/configure-Debian.yml
roles/network/tasks/lldpd.yml
roles/network/tasks/type-interfaces.yml
roles/network/tasks/type-netplan.yml
roles/packages/tasks/package-Debian.yml
roles/podman/tasks/install-Debian.yml
roles/repository/tasks/repository-Debian.yml
roles/sysdig/tasks/install-Debian.yml
roles/trivy/tasks/install-Debian.yml

partly: osism/issues#61
﻿Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>

change wait for apt lock

---

roles/network/tasks/type-netplan.yml

Co-authored-by: Bernd Müller <mueller@b1-systems.de>

network: use dict2items

---

README.md
roles/vault_unseal/defaults/main.yml
roles/vault_unseal/meta/main.yml
roles/vault_unseal/tasks/main.yml

Add vault_unseal role

---

README.md
roles/vaul_seal/defaults/main.yml
roles/vaul_seal/meta/main.yml
roles/vaul_seal/tasks/main.yml

Add vault_seal role

---

README.md
roles/vault_init/defaults/main.yml
roles/vault_init/meta/main.yml
roles/vault_init/tasks/main.yml
roles/vault_unseal/meta/main.yml

Add initial vault_init role

---

roles/network/defaults/main.yml
roles/network/tasks/cleanup-netplan.yml
roles/network/tasks/type-netplan.yml

network: remove unmanged netplan files

---

molecule/default/converge.yml
molecule/default/prepare.yml
molecule/default/prepare/configuration.yml
molecule/default/prepare/docker_compose.yml
molecule/default/prepare/kompose.yml
molecule/default/prepare/kubectl.yml
molecule/default/prepare/microcode.yml
molecule/default/prepare/motd.yml
molecule/default/prepare/podman.yml
molecule/default/prepare/repository.yml
molecule/default/prepare/trivy.yml
molecule/default/verify.yml

partly: osism/issues#63
﻿Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>

renaming ansible builtin modules in the ansible-collections-commons/molecule/default Repository

---

roles/cleanup/tasks/main.yml
roles/cleanup/tasks/packages-Debian.yml
roles/cleanup/tasks/packages-RedHat.yml
roles/cleanup/tasks/services.yml
roles/cleanup/tasks/timers-Debian.yml
roles/cleanup/tasks/timers-RedHat.yml

- Use the ansible builtin tasks in the ansible-collection-commes/roles/cleanup
- This is partly from the github issue: osism/issues#63
﻿Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>

Use ansible builtin tasks

---

roles/hosts/defaults/main.yml
roles/hosts/tasks/type-block.yml
roles/hosts/templates/hosts-template.j2

hosts: add hosts_use_dns_as_single_source_of_truth parameter

---

README.md
roles/known_hosts/defaults/main.yml
roles/known_hosts/meta/main.yml
roles/known_hosts/tasks/main.yml
roles/vault_import/defaults/main.yml
roles/vault_import/meta/main.yml
roles/vault_import/tasks/main.yml

Add known_hosts role

---

roles/systohc/tasks/main.yml

systohc: fix typo

---

molecule/default/molecule.yml
molecule/delegated/molecule.yml

molecule: fix installation of required collections

---

.github/workflows/check-yaml-syntax.yml
.github/workflows/test-role-cleanup.yml
.github/workflows/test-role-configfs.yml
.github/workflows/test-role-configuration.yml
.github/workflows/test-role-docker_compose.yml
.github/workflows/test-role-facts.yml
.github/workflows/test-role-firewall.yml
.github/workflows/test-role-hostname.yml
.github/workflows/test-role-hosts.yml
.github/workflows/test-role-ipmitool.yml
.github/workflows/test-role-kernel_modules.yml
.github/workflows/test-role-kompose.yml
.github/workflows/test-role-kubectl.yml
.github/workflows/test-role-lynis.yml
.github/workflows/test-role-microcode.yml
.github/workflows/test-role-motd.yml
.github/workflows/test-role-operator.yml
.github/workflows/test-role-packages.yml
.github/workflows/test-role-podman.yml
.github/workflows/test-role-proxy.yml
.github/workflows/test-role-repository.yml
.github/workflows/test-role-resolvconf.yml
.github/workflows/test-role-services.yml
.github/workflows/test-role-sshconfig.yml
.github/workflows/test-role-state.yml
.github/workflows/test-role-sysctl.yml
.github/workflows/test-role-sysdig.yml
.github/workflows/test-role-systohc.yml
.github/workflows/test-role-timezone.yml
.github/workflows/test-role-trivy.yml

github: run branch builds on main only

---

.github/workflows/test-role-certificates.yml
.github/workflows/test-role-cleanup.yml
.github/workflows/test-role-configfs.yml
.github/workflows/test-role-configuration.yml
.github/workflows/test-role-docker_compose.yml
.github/workflows/test-role-facts.yml
.github/workflows/test-role-firewall.yml
.github/workflows/test-role-hostname.yml
.github/workflows/test-role-hosts.yml
.github/workflows/test-role-ipmitool.yml
.github/workflows/test-role-kernel_modules.yml
.github/workflows/test-role-kompose.yml
.github/workflows/test-role-kubectl.yml
.github/workflows/test-role-lynis.yml
.github/workflows/test-role-microcode.yml
.github/workflows/test-role-motd.yml
.github/workflows/test-role-operator.yml
.github/workflows/test-role-packages.yml
.github/workflows/test-role-podman.yml
.github/workflows/test-role-proxy.yml
.github/workflows/test-role-repository.yml
.github/workflows/test-role-resolvconf.yml
.github/workflows/test-role-services.yml
.github/workflows/test-role-sshconfig.yml
.github/workflows/test-role-state.yml
.github/workflows/test-role-sysctl.yml
.github/workflows/test-role-systohc.yml
.github/workflows/test-role-timezone.yml
.github/workflows/test-role-trivy.yml

github: use ansible v5.2.0

---

.ansible-lint
.github/workflows/check-ansible-syntax.yml
roles/certificates/tasks/main.yml
roles/cleanup/tasks/services-Debian.yml
roles/cleanup/tasks/services-RedHat.yml
roles/docker_compose/handlers/main.yml
roles/docker_compose/tasks/main.yml
roles/hosts/tasks/main.yml
roles/ipmitool/tasks/main.yml
roles/known_hosts/tasks/main.yml
roles/kompose/tasks/main.yml
roles/kubectl/tasks/main.yml
roles/lynis/tasks/main.yml
roles/network/tasks/main.yml
roles/network/tasks/type-interfaces.yml
roles/network/tasks/type-netplan.yml
roles/packages/tasks/package-RedHat.yml
roles/podman/tasks/deploy.yml
roles/podman/tasks/main.yml
roles/proxy/tasks/main.yml
roles/resolvconf/tasks/main.yml
roles/services/tasks/main.yml
roles/sysctl/tasks/main.yml
roles/sysdig/tasks/main.yml
roles/trivy/tasks/main.yml

github: use our own ansible-lint action

---

roles/hosts/defaults/main.yml

hosts: add parameter documentation

---

roles/cleanup/tasks/packages-RedHat.yml

sansible -> ansible

---

roles/cleanup/tasks/packages-RedHat.yml

cleanup: use command instead of shell

---

roles/repository/tasks/repository-Debian.yml
roles/repository/vars/Debian.yml
roles/repository/vars/Ubuntu.yml

Co-authored-by: Bernd Mueller <mueller@b1-systems.de>

repository: support to add keys from a directory

---

roles/repository/tasks/repository-Debian.yml

and fileglob needs /* at the end

check if the keys directory exists have to be delegated

---

roles/known_hosts/tasks/main.yml

known_hosts: also scan ansible_host

---

roles/configuration/tasks/git.yml
roles/configuration/tasks/main.yml

configuration: use ansible.builtin

---

roles/network/defaults/main.yml
roles/network/templates/dummy.netdev.j2

added mtu size for dummy interface

---

roles/proxy/tasks/main.yml

proxy: add NO_PROXY to /etc/environment

---

molecule/default/prepare/docker_compose.yml
molecule/default/vars/docker_compose.yml

molecule: add docker repository to docker_compose

---

doc/source/index.rst
roles/cleanup/README.rst

partly of https://github.com/osism/issues/issues/185

Cleanup: Documentation for the role and variables

---

roles/configuration/tasks/git.yml

configuration: add branch to task name

---

roles/resolvconf/tasks/configure-resolv.yml

Resolvconf: Change position of the when condition

---

molecule/default/prepare/sshconfig.yml
molecule/default/vars/sshconfig.yml
roles/sshconfig/README.rst
roles/sshconfig/defaults/main.yml
roles/sshconfig/tasks/main.yml

sshconfig: get operator home directory via getent passwd

---

.zuul.yaml

Add default-branch to zuul config

---

.zuul.yaml

Publish fresh docs each time a change was merged.

Add osism-publish-tox-docs-staging job to post

---

molecule/delegated/vars/sosreport.yml
roles/sosreport/tasks/main.yml

sosreport: remove not required become

---

roles/network/README.rst

Fix documentation build error

---

plugins/modules/scan_services.py

plugins: use python3 for scan_services

---

.github/workflows/test-role-certificates.yml
.github/workflows/test-role-cleanup.yml
.github/workflows/test-role-configfs.yml
.github/workflows/test-role-configuration.yml
.github/workflows/test-role-docker_compose.yml
.github/workflows/test-role-facts.yml
.github/workflows/test-role-firewall.yml
.github/workflows/test-role-hostname.yml
.github/workflows/test-role-hosts.yml
.github/workflows/test-role-ipmitool.yml
.github/workflows/test-role-kernel_modules.yml
.github/workflows/test-role-kompose.yml
.github/workflows/test-role-kubectl.yml
.github/workflows/test-role-lynis.yml
.github/workflows/test-role-microcode.yml
.github/workflows/test-role-motd.yml
.github/workflows/test-role-operator.yml
.github/workflows/test-role-packages.yml
.github/workflows/test-role-proxy.yml
.github/workflows/test-role-repository.yml
.github/workflows/test-role-resolvconf.yml
.github/workflows/test-role-services.yml
.github/workflows/test-role-sosreport.yml
.github/workflows/test-role-sshconfig.yml
.github/workflows/test-role-state.yml
.github/workflows/test-role-sysctl.yml
.github/workflows/test-role-systohc.yml
.github/workflows/test-role-trivy.yml

Enable Ubuntu 22.04 tests

---

.github/workflows/test-role-timezone.yml
roles/timezone/defaults/main.yml
roles/timezone/tasks/main.yml

Enable Ubuntu 22.04 Tests in Role Timezone and prepare Role

---

roles/timezone/tasks/main.yml

timezone: add missing "Wait for apt lock" task

---

.zuul.yaml

Partial: https://github.com/osism/issues/issues/219

Publish docs to production instead of staging

---

roles/kernel_modules/README.rst

Be more verbose about the action of the module, amend some wording and
formatting.

Update documentation for kernel_modules role

---

README.md

README: add link to documentation

---

.ansible-lint
roles/certificates/tasks/main.yml
roles/certificates/templates/certificates.j2
roles/clevis/tasks/create-tangcrypt.yml
roles/clevis/templates/keyfile.j2
roles/configuration/tasks/git.yml
roles/configuration/templates/config-git-private-key.j2
roles/hostname/tasks/main.yml
roles/hostname/templates/config.j2
roles/motd/tasks/main.yml
roles/motd/templates/config.j2
roles/proxy/tasks/RedHat.yml
roles/resolvconf/tasks/configure-resolv.yml
roles/sysdig/tasks/install-Debian.yml
roles/sysdig/templates/config.j2

Partly osism/issues#326
Signed-off-by: Ramona Beermann <rautenberg@osism.tech>

Fix Ansible-Lint-Errors upcoming after the last Version update

---

molecule/requirements.txt

Testing older version to evaluate if there is a bug

---

roles/timezone/tasks/main.yml

timezone: fix ansible-lint warning

---

roles/network/README.rst
roles/network/defaults/main.yml
roles/network/templates/netplan/01-osism.yaml.j2

network: add vrfs

---

roles/hosts/templates/hosts-template.j2

hosts: check if hosts_interface is defined

---

roles/network/README.rst
roles/network/defaults/main.yml
roles/network/templates/netplan/01-osism.yaml.j2

This reverts commit ddb53d38f9def1e5271e2a7aa03b9f64801711f8.

Revert "network: add vrfs"

---

.ansible-lint
galaxy.yml
roles/kubectl/tasks/install-Debian.yml

Ansible-lint: Fix issues upcoming last rebuild to zuul

---

molecule/delegated/vars/packages.yml
roles/certificates/tasks/install-Debian.yml
roles/cleanup/tasks/packages-Debian.yml
roles/cleanup/tasks/packages-RedHat.yml
roles/clevis/tasks/create-tangcrypt.yml
roles/configuration/tasks/git.yml
roles/docker_compose/tasks/install.yml
roles/docker_login/tasks/main.yml
roles/ipmitool/tasks/install-Debian.yml
roles/kompose/tasks/install-url.yml
roles/kubectl/tasks/install-Debian.yml
roles/lynis/tasks/install-Debian.yml
roles/microcode/tasks/main.yml
roles/motd/tasks/configure-Debian.yml
roles/network/tasks/type-interfaces.yml
roles/network/tasks/type-netplan.yml
roles/packages/tasks/package-Debian.yml
roles/podman/tasks/install-Debian.yml
roles/repository/handlers/main.yml
roles/repository/tasks/repository-Debian.yml
roles/runc/tasks/install-Debian.yml
roles/sysdig/tasks/install-Debian.yml
roles/timezone/tasks/main.yml
roles/trivy/tasks/install-Debian.yml

Set apt lock timeout to 300 by default

---

roles/docker_login/README.rst

partly osism/testbed#1439
Signed-off-by: Tim Beermann <beermann@osism.tech>

Pull containers only from our own container registry.

---

roles/certificates/handlers/main.yml
roles/clevis/handlers/main.yml
roles/network/handlers/main.yml

Now the handlers will be checked by ansible-lint too.
This PR will solves the errors which comes up after the update.

Ansible-lint: Fix Syntax errors

---

roles/hosts/tasks/type-block.yml

Fix ansible-lint pipeline

---

roles/docker_compose/README.rst
roles/docker_compose/defaults/main.yml
roles/docker_compose/templates/docker-compose.service.j2

docker_compose: make pull of images in the service configurable

---

roles/network/tasks/type-interfaces.yml

network: use ansible_distribution_version

---

releasenotes/notes/network-default-netplan-dda52e88b415f4f2.yaml
roles/network/README.rst
roles/network/defaults/main.yml

network: use netplan as default

---

roles/clevis/README.rst
roles/clevis/defaults/main.yml
roles/clevis/handlers/main.yml
roles/clevis/meta/main.yml
roles/clevis/tasks/create-tangcrypt.yml
roles/clevis/tasks/install-Debian.yml
roles/clevis/tasks/install-RedHat.yml
roles/clevis/tasks/main.yml
roles/clevis/templates/keyfile.j2
roles/clevis/vars/Debian.yml
roles/clevis/vars/RedHat.yml

Removed by accident with ff592b2db4ccf3e3368117b015e8cbb4d2cd7d98.

Re-add clevis role

---

roles/repository/tasks/repository-Debian.yml

Closes osism/ansible-collection-commons#572

repository: use loop_control

---

roles/user/README.rst
roles/user/defaults/main.yml
roles/user/meta/main.yml
roles/user/tasks/accounts.yml
roles/user/tasks/fetch_ssh_key.yml
roles/user/tasks/keyfile.yml
roles/user/tasks/main.yml
roles/user/templates/config.j2

Allows to create and delete admin accounts on systems.

Add user role

---

roles/resolvconf/README.rst
roles/resolvconf/tasks/configure-resolv.yml

Overhaul of https://github.com/osism/ansible-collection-commons/pull/577. See commit messages.
Signed-off-by: Silvio Knizek <knizek@b1-systems.de>

Feature/get rid of ansible.posix.synchronize and rsync

---

molecule/delegated/tests/motd/debian.py
roles/motd/tasks/configure-Debian.yml
roles/motd/tasks/main.yml

Closes osism/ansible-collection-commons#540

motd: disable the dynamic MOTD news service

---

roles/motd/tasks/configure-Debian.yml

Closes osism/ansible-collection-commons#581

motd: use community.general.pamd for changes in /etc/pam.d

---

README.md
galaxy.yml
roles/network/README.md
roles/packages/README.md
roles/services/README.md
roles/sshconfig/README.md
roles/sysctl/README.md
roles/timezone/README.md

Part of https://github.com/osism/issues/issues/927

Replace osism.github.io with osism.tech

---

molecule/delegated/tests/operator.py
roles/operator/tasks/main.yml
roles/operator/vars/Debian-family.yml
roles/operator/vars/RedHat-family.yml

operator: use prefix variables for OS specific defaults

---

molecule/delegated/tests/repository/centos.py
molecule/delegated/tests/repository/debian.py
roles/repository/tasks/main.yml
roles/repository/vars/AlmaLinux-dist.yml
roles/repository/vars/CentOS-dist.yml
roles/repository/vars/Debian-dist.yml
roles/repository/vars/Rocky-dist.yml
roles/repository/vars/Ubuntu-dist.yml

repository: use prefix variables for OS specific defaults

---

molecule/delegated/tests/packages/main.py
roles/packages/tasks/main.yml
roles/packages/vars/Debian-family.yml
roles/packages/vars/RedHat-family.yml

packages: use prefix variables for OS specific defaults

---

molecule/delegated/prepare/docker_compose.yml
molecule/delegated/tests/resolvconf.py
molecule/delegated/tests/trivy/debian.py
roles/kubectl/tasks/install-RedHat-family.yml
roles/lynis/tasks/install-RedHat-family.yml
roles/microcode/tasks/main.yml
roles/network/tasks/netplan-RedHat-family.yml
roles/network/vars/Debian-family.yml
roles/network/vars/RedHat-family.yml
roles/systohc/tasks/main.yml
roles/trivy/tasks/install-Debian-family.yml

cf. https://github.com/osism/issues/issues/1002

Fix failed Ubuntu 24.04 tests

---

roles/user/defaults/main.yml
roles/user/tasks/type-default.yml

Set e.g. user_primary_group = dragon to use dragon as the primary group for users.

user: make it possible to change the primary group

---

roles/user/tasks/remote-key.yml

The download failed, when defining "github" as "key" specification.

user: fix handling of key downloads

---

molecule/delegated/tests/kubectl/debian.py
molecule/delegated/tests/kubectl/main.py
roles/kubectl/README.rst
roles/kubectl/defaults/main.yml
roles/kubectl/tasks/install-Debian-family.yml
roles/kubectl/tasks/install-RedHat-family.yml
roles/kubectl/tasks/main.yml
roles/kubectl/vars/Debian-family.yml
roles/kubectl/vars/RedHat-family.yml

needed in https://github.com/osism/ansible-collection-services/pull/1427/files#diff-fc793f8c0ac0334f684966c84fc27e57b617b5d7e4a8ca448ee752a6d6571fe5R8

kubectl: Add python-kubernetes (#881)

---

molecule/delegated/tests/resolvconf.py

- Related issue: https://github.com/osism/issues/issues/1132
- Add DNS checks using dig

resolvconf: : Enhance CI tests

---

molecule/delegated/tests/k9s.py

https://github.com/osism/issues/issues/1132

k9s: Enhance CI tests

---

molecule/delegated/tests/kubectl/main.py

https://github.com/osism/issues/issues/1132

kubectl: Enhance CI tests

---

molecule/delegated/tests/lynis/main.py

https://github.com/osism/issues/issues/1132

lynis: Enhance CI tests

---

molecule/delegated/tests/trivy/debian.py
molecule/delegated/tests/trivy/main.py
roles/trivy/tasks/install-Debian-family.yml

https://github.com/osism/issues/issues/1132

trivy: Enhance CI tests

---

roles/packages/defaults/main.yml
roles/packages/tasks/package-Debian-family.yml
roles/packages/tasks/package-RedHat-family.yml

* Remove useless packages from the cache
* Remove dependencies that are no longer required

packages: add some cleanup tasks from the cleanup role

---

molecule/delegated/prepare/sshconfig.yml
molecule/delegated/tests/sshconfig.py
molecule/delegated/vars/sshconfig.yml

related issue: https://github.com/osism/issues/issues/1132

sshconfig: Enhance CI tests

---

molecule/delegated/tests/resolvconf.py

E712 comparison to True should be 'if cond is True:' or 'if cond:'

molecule: fix flake E712 issue

---

roles/repository/defaults/main.yml
roles/repository/templates/99osism.j2

The name enable_phased_updates is wrong. It should be repository_enable_phased_updates.

repository: use repository_apt_phased_updates

---

roles/repository/defaults/main.yml
roles/repository/templates/99osism.j2

repository_apt_install_recommends: false
repository_apt_install_suggests: false
Closes osism/issues#1216

repository: make it possible to avoid recommended/suggested packages

---

roles/network/templates/vxlan.netdev.j2

Configures VXLAN multicast group IP address.

network: add Group to vxlan netdev

---

roles/network/templates/vxlan.netdev.j2
roles/network/templates/vxlan.network.j2

Related to a09d46690e0bcfeb25b515d383e2fe3eb9ddfa4f

network: to not set Group for netdev by default

---

roles/configuration/defaults/main.yml
roles/configuration/tasks/git.yml
roles/configuration/tasks/update.yml

This way it is easier to debug tasks with no_log.

configuration: make no_log configurable

---

molecule/delegated/tests/motd/debian.py
molecule/delegated/tests/motd/main.py
molecule/delegated/tests/motd/redhat.py
molecule/delegated/vars/motd.yml

molecule: enhance motd tests
