osism/ansible-collection-commons

roles/zabbix_host/tasks/main.yml

zabbix_host: fix wrong macro name

---

roles/docker_compose/templates/docker-compose.service.j2

docker-compose: use stop instead of down when stopping a service

---

roles/cleanup/defaults/main.yml

cleanup: do not remove apport + snapd by default

---

roles/systohc/defaults/main.yml
roles/systohc/tasks/main.yml

With the systohc argument it is possible to disable the role.

systohc: add systohc argument

---

.github/templates/galaxy.yml.j2

changed osism.de to osism.tech

---

roles/network/defaults/main.yml
roles/network/tasks/type-netplan.yml

9521bf66597fae2ec556a437010796925c2cda4e was the wrong approach.
Closes #222

network: fix dict2items requires a dictionary

---

molecule/delegated/converge.yml
molecule/delegated/prepare.yml

partly: osism/issues#63
﻿Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>

renaming ansible builtin modules in the ansible-collections-commons/molecule/delegated Repository

---

roles/state/tasks/main.yml

- Use the ansible.builtin.tasks in the ansible-collection-commes/roles/state Repo
- This is partly from the github issue: osism/issues#63

Use ansible builtin tasks

---

roles/configfs/tasks/main.yml

- Use the ansible.builtin.tasks in the ansible-collection-commons/roles/configfs Repo.
- This is partly from the github issue: osism/issues#63

Use ansible.builtin.tasks

---

roles/sysctl/defaults/main.yml
roles/sysctl/tasks/main.yml

The existing sysctl parameter is renamed to sysctl_defaults
and combined with the new sysctl_extra parameter. This makes
it possible to set additional parameters for specific host
groups via sysctl_extra.
Closes #277

sysctl: allow configuration of extra parameters

---

roles/configuration/tasks/main.yml

This will resolve the following deprecation note:
[DEPRECATION WARNING]: "include" is deprecated, use
include_tasks/import_tasks/import_playbook instead. This feature will be
removed in version 2.16. Deprecation warnings can be disabled by setting

configuration: use include_tasks

---

roles/sysctl/defaults/main.yml

really often so we would like to have a much higher limit as standard
in osism installations
Signed-off-by: Markus Lindenblatt <markus.lindenblatt@plusserver.com>

with standard ubuntu value of nf_conntrack_max we are reaching the limit

---

roles/sysctl/tasks/sysctl.yml

Some of the defaults only work on certain systems. Therefore,
ignore them if they cannot be set.
setting net.netfilter.nf_conntrack_max failed: sysctl: cannot
stat /proc/sys/net/netfilter/nf_conntrack_max: No such file or
directory

sysctl: ignore errors about unknown keys

---

roles/sysctl/tasks/sysctl.yml

This will fix the following issue:
TASK [osism.commons.sysctl : Set sysctl parameters on {'key':
'elasticsearch', 'value': [{'name': 'vm.max_map_count', 'value':
262144}]} nodes] ***

sysctl: fix task name

---

roles/hosts/defaults/main.yml
roles/hosts/templates/hosts-template.j2

Defining hosts_interface variable in defaults.yml is not working
correctly. The variable needs to be evaluated in the for loop to
retrieve the correct interface name of the current host.

Fix hosts_interface variable evaluation

---

roles/motd/defaults/main.yml

The previous default note was there by default because
of STIG V-71859. On environments where this is needed,
the value can be set explicitly.
Closes #296

motd: use an empty string by default for the /etc/motd

---

roles/configuration/defaults/main.yml
roles/configuration/tasks/git.yml

A PAT is simply set as a username. In order not to leak this in the
Ansible logs, no_log must be set for all tasks that use the username.
Closes #308

configuration: document use of PAT and no longer log the username

---

roles/configuration/defaults/main.yml
roles/configuration/tasks/git.yml

With the configuration_git_proxy argument it is possible
to set the HTTP proxy configuration for Git.

configuration: support proxy configuration

---

roles/network/tasks/type-netplan.yml

- Change local_action to delegate_to and use the ansible FQCN.
- This closes #322

Replace deprecated local_action

---

roles/sosreport/defaults/main.yml
roles/sosreport/meta/main.yml
roles/sosreport/tasks/main.yml

- Migrate the sosreport playbook to ansible.commons.roles
- This is partly of osism/ansible-playbooks#224

Migrate sosreport playbook to role

---

roles/repository/tasks/repository-Debian.yml

TASK [osism.commons.repository : Check if the keys directory exists] ********************
fatal: [manager1 -> localhost]: FAILED! => {"changed": false, "msg": "Permission denied"}

repository: fix "Check if the keys directory exists"

---

roles/cleanup/defaults/main.yml
roles/cleanup/tasks/cloudinit.yml
roles/cleanup/tasks/main.yml
roles/cleanup/tasks/packages-Debian.yml
roles/cleanup/tasks/packages-RedHat.yml
roles/cleanup/vars/Debian.yml
roles/cleanup/vars/RedHat.yml

Depending on how virtual systems or baremetal was deployed cloud-init
is present there. This can break things on a second boot.
Therefore, cloudinit will be removed by default from now on.
Any cloud-init logs that may exist are not removed.
Closes osism/issues#213

cleanup: remove cloudinit

---

doc/source/index.rst
roles/certificates/README.rst

- Add the documentation for the role certificates and the variables.
- This is partly https://github.com/osism/issues/issues/185

Certificates: Documentation for the role and variables

---

.ansible-lint
.yamllint.yml
.zuul.yaml
tox.ini

Run yamllint and ansible-lint as check job via tox-linters.

Add tox-linters job

---

roles/timezone/README.rst
roles/timezone/defaults/main.yml

Required by Ubuntu 22.04.
Also improve the parameter documentation.

timezone: use Etc/UTC as new default

---

roles/sysctl/defaults/main.yml

We do not use the all group in OSISM. The correct group is generic.
Closes #375

sysctl: use generic group instead of all group

---

roles/network/tasks/type-netplan.yml

The tasks do not change anything on the target host and always change. Regardless of whether changes really take place. Therefore changed_when is set to False here.

network: set changed_when=False for tasks running @ localhost

---

README.md
roles/docker_login/README.rst
roles/docker_login/defaults/main.yml
roles/docker_login/meta/main.yml
roles/docker_login/tasks/main.yml

The docker_login role can be used to login to a registry independently of the osism.services.docker role.

Add docker_login role

---

roles/hosts/templates/hosts-template.j2

If hosts_interface is not set by default the internal_interface should be used instead of the management_interface.

hosts: use internal_interface

---

roles/repository/README.rst
roles/repository/defaults/main.yml
roles/repository/tasks/repository-Debian.yml
roles/repository/templates/99osism.j2

With the enable_phased_updates parameter it is possible to control the use of phased updates on Debian/Ubuntu. Phased updates are disabled by default.
Closes osism/issues#210

repository: add enable_phased_updates parameter

---

roles/repository/README.rst
roles/repository/defaults/main.yml
roles/repository/templates/99osism.j2

Only for Debian/Ubuntu:
Forcing IPv4 transport with apt-get.

repository: add repository_apt_acquire_forceipv4

---

roles/kubectl/README.rst
roles/kubectl/defaults/main.yml
roles/kubectl/tasks/install-Debian.yml
roles/lynis/tasks/install-Debian.yml
roles/repository/tasks/repository-Debian.yml
roles/sysdig/tasks/install-Debian.yml
roles/trivy/tasks/install-Debian.yml

Do not use apt-key on Ubuntu 22.04

---

roles/motd/tasks/configure-Debian.yml

Role motd: Remove all "Wait for apt lock“ tasks

---

roles/lynis/tasks/install-Debian.yml

Role lynis: Remove all "Wait for apt lock“ tasks

---

roles/ipmitool/tasks/install-Debian.yml

Role ipmitool: Remove all "Wait for apt lock“ tasks

---

roles/kubectl/tasks/install-Debian.yml

Role kubectl: Remove all "Wait for apt lock“ tasks

---

roles/kompose/tasks/install-url.yml

Role kompose: Remove all "Wait for apt lock“ tasks

---

roles/trivy/tasks/install-Debian.yml

Role trivy: Remove all "Wait for apt lock“ tasks

---

roles/sysdig/tasks/install-Debian.yml

Role sysdig: Remove all "Wait for apt lock“ tasks

---

roles/clevis/tasks/install-Debian.yml

Role clevis: Remove all "Wait for apt lock“ tasks

---

roles/runc/tasks/install-Debian.yml

Role runc: Remove all "Wait for apt lock“ tasks

---

roles/certificates/tasks/install-Debian.yml

Role certificates: Remove all "Wait for apt lock“ tasks

---

roles/docker_login/tasks/main.yml

Role docker_login: Remove all "Wait for apt lock“ tasks

---

roles/packages/tasks/package-Debian.yml

Role packages: Remove all "Wait for apt lock“ tasks

---

roles/microcode/tasks/main.yml

Role microcode: Remove all "Wait for apt lock“ tasks

---

roles/repository/tasks/repository-Debian.yml

Role repository: Remove all "Wait for apt lock“ tasks

---

roles/cleanup/tasks/packages-Debian.yml

Role cleanup: Remove all "Wait for apt lock“ tasks

---

roles/docker_compose/tasks/install.yml

Role docker_compose: Remove all "Wait for apt lock“ tasks

---

.ansible-lint
roles/cleanup/meta/main.yml
roles/clevis/meta/main.yml
roles/configuration/tasks/git.yml
roles/motd/meta/main.yml
roles/packages/meta/main.yml
roles/packages/tasks/package-RedHat.yml
roles/repository/meta/main.yml
roles/resolvconf/meta/main.yml
roles/resolvconf/tasks/configure-resolv.yml
roles/timezone/tasks/main.yml

Rework the noqas from numbers to names.
Add some noqas for some issues found by ansible-lint localy
Partly osism/issues#496

Ansible-lint: Rework noqas

---

roles/repository/tasks/repository-Debian.yml

Add 'run_once' option to the task to ensure it runs only once on the first host in the 'manager' group

repository: run "Check if the keys directory exists"  only once

---

roles/repository/vars/Debian.yml

This way the role can be used on Debian as well.

repository: add Debian.yml file

---

roles/resolvconf/tasks/configure-resolv.yml

Make sure that the service is also activated and started so that this is boot safe. there are debian(-based) distributions where the resolvconf is not already active by default.

resolvconf: add task to start and enable systemd-resolved service

---

roles/network/vars/interfaces/ubuntu-22.04.yml

This way it is possible to also use interfaces type with Ubuntu 22.04.

network: add missing ubuntu-22.04.yml file

---

roles/hostname/README.rst
roles/hostname/defaults/main.yml
roles/hostname/tasks/main.yml
roles/hostname/templates/config.j2

This allows to use the full FQDN as hostname instead of just the short version.
Closes: osism/issues#617

hostname: add flag to use fqdn

---

roles/operator/tasks/main.yml

Using LANG=en_US.UTF-8 has some unwanted side effects, in particular using a 12h time format, which can be confusing. Use C.UTF-8 as proper international locale instead.

operator: Use C.UTF-8 as locale

---

roles/operator/README.rst
roles/operator/defaults/main.yml
roles/operator/tasks/main.yml

Supports a list of Github accounts from which the public keys are added to the authorized keys.
Related to SovereignCloudStack/issues#433

operator: add operator_authorized_github_accounts parameter

---

releasenotes/notes/netplan-permissions-13170182ceae251f.yaml
roles/network/tasks/type-netplan.yml

This will fix the following warning message:
Permissions for /etc/netplan/01-osism.yaml are too open. Netplan configuration should NOT be accessible by others.

network: reduce permission on /etc/netplan/01-osism.yaml

---

roles/known_hosts/defaults/main.yml

Changed by accident with ff592b2db4ccf3e3368117b015e8cbb4d2cd7d98.

known_hosts: fix magic groups variable

---

molecule/delegated/tests/kompose.py
molecule/delegated/tests/kubectl.py
molecule/delegated/tests/lynis.py
molecule/delegated/tests/trivy/debian.py
molecule/delegated/tests/util/util.py
roles/kompose/defaults/main.yml
roles/kompose/tasks/install-url.yml
roles/kubectl/defaults/main.yml
roles/kubectl/tasks/install-Debian.yml
roles/lynis/defaults/main.yml
roles/trivy/defaults/main.yml

**Adding dynamic arch resolution for following roles:**

Add dynamic arch resolution

---

roles/network/tasks/type-netplan.yml

/etc/network is a deprecated interface for network configuration on Ubuntu systems >= 22.04.[1]
As `/etc/network` might not exist, copying the dummy file to it can fail. So checking first if the directory exists is the cleanest way. Another alternative would be to just create `/etc/networks`, but keeping deprecated interfaces just for the sake of deprecated interfaces sounds wrong.
[1]: https://ubuntu.com/server/docs/network-configuration

Check target dir exists before writing to it

---

roles/kubectl/tasks/install-Debian.yml
roles/lynis/tasks/install-Debian.yml
roles/trivy/tasks/install-Debian.yml

cf. https://github.com/osism/issues/issues/849
Add task to remove old repository entry in kubectl, lynis and trivy role (cf. https://github.com/osism/ansible-collection-commons/pull/570)

Add tasks to remove old architecture-dependent repository

---

.zuul.yaml

the used regex there works as well, but more so by accident
it would also match e.g. "azuulayaml" files etc.
Signed-off-by: Sven Kieske <kieske@osism.tech>

fix unescaped dots in .zuul.yaml

---

.ansible-lint

The modules are now installed by the ansible-lint job.

ansible-lint: do not mock most modules

---

molecule/delegated/tests/certificates.py
roles/certificates/defaults/main.yml
roles/certificates/vars/Debian-family.yml
roles/certificates/vars/RedHat-family.yml

The certificates_ca_package_name can be an OS specific parameter that cannot be changed.

certificates: move certificates_ca_package_name parameter

---

roles/sshconfig/tasks/main.yml

By setting sshconfig_private_key_file = "" it's possible to skip the "Ensure config for each host exist" task. This way it's possible to use the role to only write extra ssh config.
This is necessary if you initially set up the manager from the seed and have to configure certain SSH parameters to reach the Git server.

sshconfig: allow to skip "Ensure config for each host exist"

---

roles/known_hosts/defaults/main.yml
roles/known_hosts/tasks/main.yml

With known_hosts_delete it is possible to delete entries from the known_hosts file.

known_hosts: make it possible to delete entries

---

roles/user/defaults/main.yml
roles/user/templates/config.j2

With the user_sudoers parameter it's possible to change the content of the user sudoers files. The default is "ALL=(ALL:ALL) NOPASSWD: ALL".

user: add user_sudoers parameter

---

roles/user/tasks/remote-key.yml

If you set key to github, the keys are fetched from GitHub. It is not necessary to enter the full URL in this case.

user: add shortcut to fetch keys from github

---

molecule/delegated/tests/configuration/main.py
roles/configuration/tasks/git.yml

https://docs.ansible.com/ansible/2.9/modules/git_module.html currently sets 0750 for the toplevel directory
(according to predefined umask). Setting "umask" alone is not enough, it seems that a "umask" on " ansible.builtin.git" only affects the file contained in the clone directory.

Change permissions for checkout folder

---

roles/motd/defaults/main.yml
roles/motd/handlers/main.yml
roles/motd/tasks/configure-Debian-family.yml
roles/motd/tasks/main.yml

Currently the motd is not displayed when performing a SSH login.
As logins in CSP environments are primarily carried out via SSH, we activate this here, as otherwise the configuration of a Motd would make little sense. This change ignores Redhat environments, because i do not have access to such a environment.

Show motd on ssh login

---

roles/packages/tasks/main.yml
roles/packages/tasks/package-Debian-family.yml

This task is only necessary when using the role on Debian.

packages: move "Set apt_cache_valid_time variable to default value"

---

roles/packages/defaults/main.yml

The `lvm2` package is not installed by default on CentOS and Debian, but required by `/opt/configuration/scripts/deploy/100-ceph-services.sh`.

Packages: Add lvm2 to required_packages_default

---

roles/network/defaults/main.yml
roles/network/templates/netplan/01-osism.yaml.j2

With network_dummy_devices it is possible to configure dummy devices.
https://netplan.readthedocs.io/en/latest/netplan-yaml/#properties-for-device-type-dummy-devices

network: add dummy-devices

---

molecule/delegated/tests/packages/debian.py
molecule/delegated/tests/packages/main.py
molecule/delegated/tests/packages/redhat.py
roles/packages/defaults/main.yml
roles/packages/tasks/package-Debian-family.yml

With the packages_needstart_mode it is possible to change the needstart mode. Possible values are a (auto), i (interactive) and l (list only).
The default value is l (list only). The Ubuntu default is i (interactive). We prefer to only list services that should be restarted.

packages: make needrestart mode configurable

---

roles/network/templates/netplan/01-osism.yaml.j2

dummy-devices only usable with netplan >= 0.107

network: only use dummy-devices on ubuntu >= 24.04

---

roles/packages/vars/Debian-family.yml

The /sbin/dhclient binary is required by the octavia-interface.service and is not installed by default on Debian.

packages: install isc-dhcp-client on Debian/Ubuntu

---

roles/packages/defaults/main.yml

Will be required in future to be able to execute prepared plays directly on the node and to be able to manage static configurations on the nodes in a central Git repository.

packages: install git by default

---

roles/proxy/defaults/main.yml
roles/proxy/tasks/main.yml

With the proxy_enable parameter it is possible to disable the proxy configuration. This makes it easier to configure global proxy parameters (via environment or group_vasr) and to skip them via host_vars only for specific hosts.

proxy: add proxy_enable parameter

---

roles/sysctl/defaults/main.yml

Related to https://gitlab.com/yaook/operator/-/commit/1e42eda64fac8045baeae1d88e865c5db70cc25b
Closes osism/issues#1155

sysctl: fs.inotify.max_user_instances = 1024 @ k3s_node

---

roles/kubectl/defaults/main.yml
roles/kubectl/tasks/install-Debian-family.yml

- raise version to current 1.32 release
- drop previous gpg keys before adding the new key to prevent an occured validation problem

update kubectl to current release

---

roles/network/defaults/main.yml
roles/network/tasks/main.yml
roles/network/tasks/vxlan-interfaces.yml
roles/network/templates/vxlan.netdev.j2
roles/network/templates/vxlan.network.j2

Sadly netplan doesn't allow to create vxlan interfaces so we create the netdev/network files for systemd-networkd directly.

network: allow to create vxlan interfaces

---

roles/network/defaults/main.yml
roles/network/tasks/vxlan-interfaces.yml
roles/network/templates/vxlan.netdev.j2
roles/network/templates/vxlan.network.j2

Currently the definition for vxlans is an array of mappings where the index and the value of the name key form the name of the networkd unit's file. Any change to the order of the array will result in a leaked unit with the old index, which is unexpected from a user's perspective and needs to be cleaned up.
The name already needs to be unique, since it is used as the interface's name. Therefore the structure could also be a mapping using the name as keys and filename, e.g.:
```
network_vxlan_interfaces:
vxlan0:
vni: ..
local_ip: ..
..
vxlan1:
...
```
This ensures unique interface names, which are also usable as filenames. Changing an interface name would still leak a file with the old name, but that would be expected when deleting resources from ansible.

Restructure vxlan definitions

---

roles/network/templates/vxlan.netdev.j2

Specifies the MAC address to use for the device, or takes the special value "none". When "none", systemd-networkd does not request the MAC address for the device, and the kernel will assign a random MAC address.

network: add MACAddress to vxlan netdev

---

.github/workflows/publish-collection.yml

This reverts commit ebc444afda291b7076f55fc06f0d9476268f3ec0.
Does not work with current Ansible version.

Revert "chore(deps): update dependency python to 3.13 (#801)"

---

roles/sysctl/defaults/main.yml

sysctl: net.netfilter.nf_conntrack_max = 1048576 on network nodes
